config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  resources :libraries
  resources :collaborators
  resources :deliveries
  resources :subscribers
  root 'home#index'
end

app/views/shared/_navigation.html.erb
<div id="topheader">
  <nav class="navbar navbar-default header" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <ul class="nav navbar-nav">
          <li class="<%= 'active' if current_page?(root_path) %>"> 
            <%= link_to root_path do  %> Главная
              <%= (content_tag :span, "(current)", :class => "sr-only") if current_page?(root_path) %>
            <% end %>
          </li>          
          <li class="<%= 'active' if current_page?(libraries_path) %>">  
            <%= link_to libraries_path do %> Библиотеки
              <%= (content_tag :span, "(current)", :class => "sr-only") if current_page?(libraries_path) %>
            <% end %>
          </li>
          <li class="<%= 'active' if current_page?(books_path) %>">
            <%= link_to books_path do %>Книги
              <%= (content_tag :span, "(current)", :class => "sr-only") if current_page?(books_path) %>
            <% end %>
          </li>
          <li class="<%= 'active' if current_page?(collaborators_path) %>">  
            <%= link_to collaborators_path do %> Cотрудники
              <%= (content_tag :span, "(current)", :class => "sr-only") if current_page?(collaborators_path) %>
            <% end %>
          </li>
          <li class="<%= 'active' if current_page?(subscribers_path) %>">  
            <%= link_to subscribers_path do %> Абоненты
              <%= (content_tag :span, "(current)", :class => "sr-only") if current_page?(subscribers_path) %>
            <% end %>
          </li>
          <li class="<%= 'active' if current_page?(deliveries_path) %>">  
            <%= link_to deliveries_path do %> Выдача книг
              <%= (content_tag :span, "(current)", :class => "sr-only") if current_page?(deliveries_path) %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>