config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  resources :libraries
  resources :collaborators
  resources :deliveries
  resources :subscribers
  root 'home#index'
end

app/models/library.rb
class Library < ApplicationRecord
    has_many  :books, dependent: :delete_all
    validates :number,presence: true,
                    length: { maximum: 100 } 
                    
    validates :name, presence: true,
                    length: { maximum: 1000 }
    validates :adress, presence: true,
                    length: { maximum: 500 }
end 

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
    def index
        @libraries = Library.all
    end
    
    def show
        @library = Library.find(params[:id])
    end
    
    def new
        @library = Library.new
    end
    
    def edit
        @library = Library.find(params[:id])
    end
    
    def create
        # @book = Book.find(params[:book_id])
        # @library = Library.new(library_params)
        
        @library = Library.create(library_params)
        if @library.save
        redirect_to @library
        else
        render 'new'
        end
    end
    
    def update
        @library = Library.find(params[:id])
    
        if @library.update(library_params)
        redirect_to @library
        else
        render 'edit'
        end
    end
    
    def destroy
        @library = Library.find(params[:id])
        @library.destroy
    
        redirect_to libraries_path
    end
    
    private
        def library_params
        params.require(:library).permit(:number, :name, :adress)
        end
    
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_with model: @library, local: true do |form| %>

  <% if @library.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@library.errors.count, "error") %> prohibited
        this library from being saved:
      </h2>
      <ul>
        <% @library.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group row">
    <%= form.label :number, class:"col-sm-2 col-form-label" do %> Номер<% end %>
    <div class="col-sm-10">
      <%= form.text_field :number, class:"form-control" %> 
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :name, class:"col-sm-2 col-form-label" do %> Имя <% end %>
      <div class="col-sm-10"> 
        <%= form.text_area :name, class:"form-control" %>
      </div>
  </div>

  <div class="form-group row">
    <%= form.label :adress, class:"col-sm-2 col-form-label" do %> Адрес <% end %>
      <div class="col-sm-10">
        <%= form.text_area :adress, class:"form-control" %>
      </div>
  </div>

  <p>
    <%= form.submit "Выполнить", class: 'btn-success btn-lg' %>
  </p>

<% end %>

app/views/libraries/edit.html.erb
<h1>Редактирование библиотеки</h1>

<%= render 'form' %>

<%= link_to 'Назад', libraries_path, class:"btn btn-link" %>

app/views/libraries/index.html.erb
<h1>Список библиотек</h1>
<table class="table table-bordered table-dark hidden-line">
  <thead>
    <tr class="line-white">
    <th>ID</th>
      <th>Номер</th>
      <th>Имя</th>
      <th>Адрес</th>
    </tr>
  </thead>
  <tbody>
    <% @libraries.each do |library| %>
      <tr>
      <td><%= library.id %></td>
        <td><%= library.number %></td>
        <td><%= library.name %></td>
        <td><%= library.adress %></td>
        <td nowrap style="border: 0px"><%= link_to 'Просмотр', library_path(library), class: "btn btn-primary btn-xs" %>
          <%= link_to 'Редактирование', edit_library_path(library), class: "btn btn-info btn-xs" %>
          <%= link_to 'X', library_path(library),
                method: :delete,
                data: { confirm: 'Удалить?' },
                class: 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
  <%= link_to new_library_path, class:"btn btn-success" do %>
    <i class="glyphicon glyphicon-plus"></i> Новая библиотека
  <% end %>

app/views/libraries/new.html.erb
<h1>Новая библиотека</h1>

<%= render 'form' %>

<%= link_to 'Назад', libraries_path, class:"btn btn-link" %>

app/views/libraries/show.html.erb
<p>
  <strong>Номер:</strong>
  <%= @library.number %>
</p>

<p>
  <strong>Имя:</strong>
  <%= @library.name %>
</p>

<p>
  <strong>Адрес:</strong>
  <%= @library.adress %>
</p>

<%= link_to 'Редактирование', edit_library_path(@library), class: "btn btn-info" %> |
<%= link_to 'Назад', libraries_path, class:"btn btn-link" %>