config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  resources :libraries
  resources :collaborators
  resources :deliveries
  resources :subscribers
  root 'home#index'
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to  :library
    has_many :deliveries, dependent: :delete_all
    validates :library_id, presence: true
    # has_many :deliveries
    # has_many :subscribers, through: :deliveries
    validates :TitleOfTheBook, presence: true,
                length: { maximum: 2000 }
    validates :author, presence: false,
                length: { maximum: 1000 }
    validates :cipher, presence: true,
                    length: { maximum: 100 }
    validates :publishing_house,  allow_blank: true,
                            length: { maximum: 256 } 
    validates :TheYearOfPublishing, allow_blank: true, numericality: { only_integer: true }
    validates :price,allow_blank: true, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }, :numericality => {:han_or_equal_to => 2, :less_than => 1000000000}
    validates :receipt_date,allow_blank: true, date: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
        def index
            @books = Book.all
        end
        
        def show
            @book = Book.find(params[:id])
        end
        
        def new
            @book = Book.new
        end
        
        def edit
            @book = Book.find(params[:id])
        end
        
        def create            
            @book = Book.create(book_params)          
            if @book.save
            redirect_to @book
            else
            render 'new'
            end
        end
        
        def update
            @book = Book.find(params[:id])
        
            if @book.update(book_params)
            redirect_to @book
            else
            render 'edit'
            end
        end
        
        def destroy
            @book = Book.find(params[:id])
            @book.destroy
        
            redirect_to books_path
        end
        
        private
            def book_params
                params.require(:book).permit( :library_id, :TitleOfTheBook, :author, :cipher, :publishing_house, :TheYearOfPublishing, :price,:receipt_date)
            end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model: @book, local: true do |form| %>

  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@book.errors.count, "error") %> prohibited
        this book from being saved:
      </h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :library_id, class:"col-sm-2 col-form-label" do %> Библиотека <% end %>
    <div class="col-sm-10">
       <%= form.select :library_id, options_for_select(Library.all.collect{ |s| [s.number+' '+s.name, s.id]}), {}, {class: "form-control form-control-lg"}  %>
    </div>
  </div> 


  <div class="form-group row">
    <%= form.label :TitleOfTheBook, class:"col-sm-2 col-form-label" do %> Название <% end %>
      <div class="col-sm-10">
        <%= form.text_field :TitleOfTheBook,class:"form-control" %>
      </div>
  </div>

  <div class="form-group row">
    <%= form.label :author,class:"col-sm-2 col-form-label" do %> Автор <% end %> 
      <div class="col-sm-10">
        <%= form.text_field :author,class:"form-control" %>
      </div>
  </div>

  <div class="form-group row">
    <%= form.label :cipher, class:"col-sm-2 col-form-label" do %> Шифр <% end %> 
    <div class="col-sm-10">
      <%= form.text_area :cipher, class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :publishing_house, class:"col-sm-2 col-form-label" do %> Издательство <% end %> 
    <div class="col-sm-10">
      <%= form.text_area :publishing_house, class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :price, class:"col-sm-2 col-form-label" do %> Год издания <% end %>
    <div class="col-sm-10">
      <%= form.text_area :TheYearOfPublishing, class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :price, class:"col-sm-2 col-form-label" do %> Цена <% end %>
    <div class="col-sm-10">
      <%= form.text_area :price, class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :receipt_date, class:"col-sm-2 col-form-label" do %> Дата поступления <% end %> 
    <div class="col-sm-10">
      <%= form.text_area :receipt_date, class:"form-control" %>
    </div>
  </div>

 
  <p>
    <%= form.submit "Выполнить",  class: 'btn-success btn-lg' %>  
  </p>    
<% end %>

app/views/books/edit.html.erb
<h1>Редактирование</h1>

<%= render 'form' %>

<%= link_to 'Назад', books_path, class:"btn btn-link" %>

app/views/books/index.html.erb
  <h1>Список книг</h1>
  <table class="table table-bordered table-dark hidden-line " >
    <thead>
      <tr class="line-white">
      <th cope="col">ID</th>
        <th cope="col">Библиотека</th>
        <th cope="col">Название книги</th>
        <th cope="col">Автор</th>
        <th cope="col">Шифр</th>
        <th cope="col">Издательство</th>
        <th cope="col">Год издания</th>
        <th cope="col">Цена</th>
        <th cope="col">Дата поступления</th>
      </tr>
    </thead>
  <tbody>
    <% @books.find_each do |book| %>
      <tr>
      <td><%= book.id%></td>
        <td>
            <%= Library.all.find(book.library_id).number %> 
            <%= Library.all.find(book.library_id).name %>
        </td>
        <td><%= book.TitleOfTheBook %></td>
        <td><%= book.author %></td>
        <td><%= book.cipher %></td>
        <td><%= book.publishing_house %></td>
        <td><%= book.TheYearOfPublishing %></td>
        <td><%= book.price %></td>
        <td><%= book.receipt_date %></td>
        <td nowrap style="border: 0px">
          <%= link_to 'Просмотр', book_path(book), class: "btn btn-primary btn-xs" %>
          <%= link_to 'Редактирование', edit_book_path(book), class: "btn btn-info btn-xs" %>
          <%= link_to 'X', book_path(book),
                  method: :delete,
                  data: { confirm: 'Удалить' }, 
                  class: 'btn btn-danger btn-xs' %>
          </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= link_to new_book_path, class:"btn btn-success" do %>
    <i class="glyphicon glyphicon-plus"></i> Новая книга
<% end %>
   
            

app/views/books/new.html.erb
<h1>Новая книга</h1>

<%= render 'form' %>

<%= link_to 'Назад', books_path, class:"btn btn-link" %>

app/views/books/show.html.erb
<div style="font-size:22px">
  <p>
    <strong>Библиотека:</strong>
    <%= @book.library_id %>
  </p>

  <p>
    <strong>Название книги:</strong>
    <%= @book.TitleOfTheBook %>
  </p>

  <p>
    <strong>Автор:</strong>
    <%= @book.author %>
  </p>

  <p>
    <strong>Шифр:</strong>
    <%= @book.cipher %>
  </p>
  <p>
    <strong>Издательство:</strong>
    <%= @book.publishing_house %>
  </p>
  <p>
    <strong>Год издания:</strong>
    <%= @book.TheYearOfPublishing %>
  </p>
  <p>
    <strong>Цена:</strong>
    <%= @book.price %>
  </p>
  <p>
    <strong>Дата поступления:</strong>
    <%= @book.receipt_date %>
  </p>

  <%= link_to 'Редактирование', edit_book_path(@book), class: "btn btn-info btn-lg " %> |
  <%= link_to 'Назад', books_path, class:"btn btn-link" %>
</div>