config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  resources :libraries
  resources :collaborators
  resources :deliveries
  resources :subscribers
  root 'home#index'
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  belongs_to :library
  has_many :deliveries
  has_many :books, through: :deliveries
  validates :ticket, :phone, numericality: { only_integer: true }
  validates :adress, presence: true,
                    length: { maximum: 1000 }
  validates :surname, :name,  presence: true,
                    length: { maximum: 100 }
  validates :patronymic,allow_blank: true,length: { maximum: 100 }
  validates :phone, :format => { :with => /^(\s*)?(\+)?([- _():=+]?\d[- _():=+]?){10,14}(\s*)?$/, multiline:true }
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
        def index
            @subscribers = Subscriber.all
        end
        
        def show
            @subscriber = Subscriber.find(params[:id])
        end
        
        def new
            @subscriber = Subscriber.new
        end
        
        def edit
            @subscriber = Subscriber.find(params[:id])
        end
        
        def create
            @subscriber = Subscriber.new(subscriber_params)
            if @subscriber.save
            redirect_to @subscriber
            else
            render 'new'
            end
        end
        
        def update
            @subscriber = Subscriber.find(params[:id])        
            if @subscriber.update(subscriber_params)
            redirect_to @subscriber
            else
            render 'edit'
            end
        end
        
        def destroy
            @subscriber = Subscriber.find(params[:id])
            @subscriber.destroy
        
            redirect_to subscribers_path
        end
        
        private
            def subscriber_params
             params.require(:subscriber).permit( :library_id, :ticket, :surname, :name, :patronymic, :adress, :phone)
            end
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/_form.html.erb
<%= form_with model: @subscriber, local: true do |form| %>

  <% if @subscriber.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@subscriber.errors.count, "error") %> prohibited
        this subscriber from being saved:
      </h2>
      <ul>
        <% @subscriber.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="form-group row">
    <%= form.label :library_id, class:"col-sm-2 col-form-label" do %> Библиотека <% end %>
    <div class="col-sm-10">
      <%= form.select :library_id, options_for_select(Library.all.collect{ |s| [s.number+' '+s.name, s.id]}), {}, {class: "form-control form-control-lg"}  %>
    </div>
  </div>  

  <div class="form-group row">
    <%= form.label :ticket, class:"col-sm-2 col-form-label" do %> Номер билета <% end %>
    <div class="col-sm-10">
      <%= form.text_field :ticket, class:"form-control" %> 
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :surname, class:"col-sm-2 col-form-label" do %> Фамилия <% end %>
    <div class="col-sm-10">
      <%= form.text_field :surname, class:"form-control" %> 
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :name, class:"col-sm-2 col-form-label" do %> Имя <% end %>
      <div class="col-sm-10"> 
        <%= form.text_area :name, class:"form-control" %>
      </div>
  </div>

  <div class="form-group row">
    <%= form.label :patronymic, class:"col-sm-2 col-form-label" do %> Отчество <% end %>
      <div class="col-sm-10">
        <%= form.text_area :patronymic, class:"form-control" %>
      </div>
  </div>    

  <div class="form-group row">
    <%= form.label :adress, class:"col-sm-2 col-form-label" do %> Адрес <% end %>
      <div class="col-sm-10"> 
        <%= form.text_area :adress, class:"form-control" %>
      </div>
  </div>

  <div class="form-group row">
    <%= form.label :phone, class:"col-sm-2 col-form-label" do %> Телефон <% end %>
      <div class="col-sm-10">
        <%= form.text_area :phone, class:"form-control" %>
      </div>
  </div>

  <p>
    <%= form.submit "Выполнить", class: 'btn-success btn-lg' %>
  </p>

<% end %>

app/views/subscribers/edit.html.erb
<h1>Редактирование информации об абоненте</h1>

<%= render 'form' %>

<%= link_to 'Назад', subscribers_path, class:"btn btn-link" %>

app/views/subscribers/index.html.erb
<h1>Список абонентов</h1>
<table class="table table-bordered table-dark hidden-line">
  <thead>
    <tr class="line-white">
      <th>Библиотека</th>
      <th>Номер билета</th>
      <th>Фамилия</th>
      <th>Имя</th>
      <th>Отчество</th>
      <th>Адрес</th>
      <th>Телефон</th>
    </tr>
  </thead>
  <tbody>
    <% @subscribers.each do |subscriber| %>
      <tr>
        <td>
          <%= Library.all.find(subscriber.library_id).number %> 
          <%= Library.all.find(subscriber.library_id).name %>
        </td>
        <td><%= subscriber.ticket %></td>
        <td><%= subscriber.surname %></td>
        <td><%= subscriber.name %></td>
        <td><%= subscriber.patronymic %></td>                
        <td><%= subscriber.adress %></td>
        <td><%= subscriber.phone %></td>
        <td nowrap style="border: 0px"><%= link_to 'Просмотр', subscriber_path(subscriber), class: "btn btn-primary btn-xs" %>
          <%= link_to 'Редактирование', edit_subscriber_path(subscriber), class: "btn btn-info btn-xs" %>
          <%= link_to 'X', subscriber_path(subscriber),
                method: :delete,
                data: { confirm: 'Удалить?' },
                class: 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
  <%= link_to new_subscriber_path, class:"btn btn-success" do %>
    <i class="glyphicon glyphicon-plus"></i> Новый абонент
  <% end %>

app/views/subscribers/new.html.erb
<h1>Новый абонент</h1>

<%= render 'form' %>

<%= link_to 'Назад', subscribers_path, class:"btn btn-link" %>

app/views/subscribers/show.html.erb
<p>
  <strong>Библиотека:</strong>
  <%= @subscriber.library_id %>
</p>

<p>
  <strong>Номер библиотеки:</strong>
  <%= @subscriber.ticket %>
</p>

<p>
  <strong>Фамилия:</strong>
  <%= @subscriber.surname %>
</p>

<p>
  <strong>Имя:</strong>
  <%= @subscriber.name %>
</p>

<p>
  <strong>Отчество:</strong>
  <%= @subscriber.patronymic %>
</p>



<p>
  <strong>Адрес:</strong>
  <%= @subscriber.adress %>
</p>

<p>
  <strong>Телефон:</strong>
  <%= @subscriber.phone %>
</p>

<%= link_to 'Редактирование', edit_subscriber_path(@subscriber), class: "btn btn-info" %> |
<%= link_to 'Назад', subscribers_path, class:"btn btn-link" %>